version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: "nachosalvador-es"
    command: jekyll serve --watch --force_polling --livereload --verbose
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
